name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/example-nginx:latest, ${{ secrets.DOCKERHUB_USERNAME }}/example-nginx:v.0-${{ github.run_attempt }}
      - 
        name: Update Helm value in Config Repo
        run: |
          git clone https://github.com/minhman1504/Udacity-Capstone-Project-Config
          cd Udacity-Capstone-Project-Config/
          ls -al
          echo "image: ${{ secrets.DOCKERHUB_USERNAME }}" > values.yaml
          echo "tag: ${{ secrets.DOCKERHUB_USERNAME }}/example-nginx:v.0-${{ github.run_attempt }}" >> values.yaml
          
          git commit -m "update values.yaml"
          git push -u origin master
          
          echo "Updata success !"
